### ISSUE TITLE
Initializing in Server: web directory / relative URL

### ISSUE THREAD

**Issue by Andy-Can** [AndrewAtLarge/WebQuiz#10]
Hey Andrew, webquiz looks awesome and I'm excited to get it configured for a CS class. I'm running into some issues / confusion on the final steps though.

I've had a network admin make server space for a class website. The idea is to have a "Webquiz" section mapped to different units.

The admin installed webquiz / latex on the server so I can send .tex files over from my local machine and compile them on the server. 

How should I go about initializing it?  I have access to a folder where I can drop web files which are accessible online.

I made the web directory this folder, and the relative URL just a a folder to house the web files. 
I'm getting the error:

<img width="598" alt="Screen Shot 2020-05-13 at 2 07 11 PM" src="https://user-images.githubusercontent.com/65306284/81848396-0ea04580-9523-11ea-990a-9a24acefaba2.png">

I'm new to web devolopment so any help is greatly appreciated!

Thank You!

**Comment by AndrewAtLarge** [comment]
You don't say whether you server is unix, mac or windows. I think that your server is probably running linux, but I am guessing.

As the error message says, the last step of the initialisation above is failing because you need to run the initialisation either from an administrator account (windows) or using sudo (linux/mac), for which you would need the root password.

I need more information before I can tell you what the correct settings should be as your set up is not clear to me. From your screenshot it looks like you are trying to install the webquiz css and javascript files into the directory /w/216online but I suspect that this is not what you actually want to do because this looks to me like a relative URL for a course on your web pages. Even if it is correct on the next line you are saying that the relative URL for this directory is `/quiz_files`, which is inconsistent.

Can you please tell me:
1.  What operating system you are using
2. The full path of the directory where you want to installed the css and javascript files
3. The full path for the root of your web directory (that is, the directory that see see when you go to the URL `www.<your web site>/`

If you give me this information I can suggest what you should be doing.

**Comment by Andy-Can** [comment]
Sorry for the lack of detail, and my ineptitude on web dev.

It's a linux server. 
You are right, the URL to the website is [(https://216online.eecs.umich.edu/)],
so my website index file is placed in the /w/216online directory.

I want a page "https://216online.eecs.umich.edu/webquizes" where I can index 4 or so quizzes. 

Let me know if you need any more information. I'm guessing I'll need to get the admin to install for me.

Thank You!

**Comment by Andy-Can** [comment]
Hey Andrew,
I was able to successfully able to troubleshoot this issue : )
For those who face a similar problem, make sure the network administrator enables sudo privileges for the virtual host you are using.
Thanks again.

**Comment by AndrewAtLarge** [comment]
Great. Glad that you have gotten it to work.
