### ISSUE TITLE
Unable to compile without errors

### ISSUE THREAD

**Issue by kariuolevi** [AndrewAtLarge/WebQuiz#2]
I tried to compile a sample quiz and received the error below. Could you please help me on how to proceed?

![issue](https://user-images.githubusercontent.com/10488426/58927675-37875a80-8758-11e9-9ccc-ab58aa1dc67f.jpg)

**Comment by AndrewAtLarge** [comment]
I opened this example in TeXShop and for me this example compiles without errors using XeLaTeX. The log file that you show have is different from what I expect because it shows that webquiz-ini.code.tex is being loaded twice.

Can you please tell me what you see if you open up a terminal window and type: 
`webquiz --version`
You should see `webquiz version 5.2`.

I think that you have an old version of the code, ni which case updating may fix your problem, but this still would not explain the error you are seeing as I have never come across this. It may also be an encoding problem.

**Comment by kariuolevi** [comment]
I updated the packages and now it compiles without a problem. Webquiz is version 5.2. Thank you very much for your help.

Best regards,
  Kari

**Comment by AndrewAtLarge** [comment]
Solved by updating packages.
