### ISSUE TITLE
Is it possible to initialize without sudo privileges?

### ISSUE THREAD

**Issue by done-with-fish** [AndrewAtLarge/WebQuiz#3]
I don't have sudo privileges on my university network, which is where my webpage is hosted.

I *really* like this software and want to use it to write quizzes on my local machine and push the html to my university webpage. Is this workflow possible, given that I don't have sudo privileges?

**Comment by AndrewAtLarge** [comment]
You should not need sudo privileges to use WebQuiz on your university server but the real answer to your question depends on what you mean by "push the html  to my university webpage". In order to use WebQuiz on an "external" server you need to copy the files from the webquiz-www directory (at least the javascript and css files and with the same directory structure) onto the server and then set webquiz-url so that it points to the relative URL for webquiz-www directory on your server. The webquiz-www can be anywhere on your web server, so putting them in your "personal" web page is fine. Once these files are in place you would then have to push each quiz, including all of the associated files that webquiz, generates to your web server.

If you only have access to your "personal" or "unit of study" web page on the server, and in particular you are not able to upload individual files to the server, then it will be difficult to get this to work. For example, if your university pages are all hosted inside a CMS like canvas or blackboard then I don't see a straightforward way of getting this to work because these systems activity strip css and javascript from any pages that are uploaded.

If you tell me more about your set up I can try and talk you through what needs to be done in more detail.

**Comment by done-with-fish** [comment]
That's encouraging to hear.

Here's my set-up:

My university webpage is hosted at: https://services.math.duke.edu/~bfitzpat/

I maintain the page by writing html files on my laptop and uploading them to the ~/public_html directory in my university account. So, I can upload individual files to the server.

I'd like to be able to write quizzes on my laptop and then push them to my web server when they're ready.

I see that the webquiz directory has a docs/www subdirectory. I can easily put the www directory on my page. How would I proceed from there?

**Comment by AndrewAtLarge** [comment]
Great. Setting this up should be easy then. Run the initialisation to install the web components on your laptop and put them in your public_html equivalent directory on your laptop and then mirror this configuration on your server so that the directory structure on both your laptop and server look something like:

```
    public_html/WebQuiz/css
                       /js
```
If you have  same username on both your server and your laptop then you can set `webquiz-url`, in the webquiz settings, to be `~bfitzpat/WebQuiz`. If you have different usernames and then you can either create a new account on your laptop and put the quizzes in the `public_html` directory for this account or you could put the tex/html files for your quizzes inside the `public_html/WebQuiz`, say in the directory `public_html/WebQuiz/quizzes`, and define `webquiz-url` as a relative URL `../`. This way you will be able to compile and view the quizzes on your laptop and they will work on your departments web server when you just copy them across.

**Comment by done-with-fish** [comment]
Working!

I ended up putting `css` and `js` in `~/public_html/webquiz` on my university account. Then I set `webquiz-url` and `webquiz-www` to `math.duke.edu/~bfitzpat/webquiz`. Now I can write and view quizzes on my laptop and push the html and accompanying directories to my webpage to publish the quizzes.

I'm really looking forward to using this tool! Thanks a lot for writing this program.

**Comment by AndrewAtLarge** [comment]
Excellent. Glad that you've gotten it working. I'll add something to the manual in the release diving more details about how dual configuration on a laptop and a server and this is a pretty common I think.
