### ISSUE TITLE
Feature Request (pdfQuiz)

### ISSUE THREAD

**Issue by pablgonz** [AndrewAtLarge/WebQuiz#6]
I know that the spirit of WebQuiz is not the pdf format, but, I expose my idea as a request.

You could adapt the WebQuiz to create a quiz in `.pdf` format using `ocgx2` and `tcolorbox`?

The visual style used by `WebQuiz` is clear and striking for a student, I think you can get something very close using `tcolorbox` and for the alternatives/questions I think `ocgx2` fits well.

My reasoning, some teachers don't have access to a decent server to be able to use all the power of `WebQuiz`, but, if we can create a good interactive `pdf` :)

- https://tex.stackexchange.com/a/494051
- https://tex.stackexchange.com/a/492768
- https://tex.stackexchange.com/a/403330

I don't know much about `Python3`, I just know it's _very flexible_ and maybe it can be adjusted to this.

It's just an idea, if it's not feasible, close this issues.

Thank you for your time.

**Comment by AndrewAtLarge** [comment]
This would be possible but it would take a lot of work to produce interactive PDF versions of these quizzes. This could be done entirely in the latex class file, so no python required. In fact, this would really be an entirely new package because currently the LaTeX output is only for checking the questions, not for displaying the quiz. It's a nice idea but not something that I have time to work on now.

Andrew
